dimagi/commcare-j2me

core/src/org/javarosa/xpath/expr/XPathFuncExpr.java, core/test/org/javarosa/xpath/test/XPathEvalTest.java
=> Add upper-case and lower-case

core/src/org/javarosa/core/util/DAG.java
Upgraded DAG datatype used during purge to support edge relationships.
X-Requested: JavaRosa, CommCare, CommCareAndroid
=> Extension Cases

core/src/org/javarosa/form/api/FormEntryController.java, core/src/org/javarosa/form/api/FormEntryModel.java
Functions to support walking forms without affecting the current state of the form.
=> Threadsafe form walk

j2me/form-entry/src/org/javarosa/formmanager/api/JrFormEntryController.java, j2me/form-entry/src/org/javarosa/utilities/media/MediaUtils.java
Produces logs like `media> start something.mp3`
Left the filename extension so it's easier to distinguish between audio and video.
=> Audio logs

core/src/org/javarosa/core/model/instance/utils/TreeUtilities.java, core/src/org/javarosa/core/util/DataUtil.java
Bugfix for serious predicate evaluation issue where in some circumstances predicates in external instances would merge subsequent predicates rather than perform a union/filter
=> Fixture predicate bug fix

core/src/org/javarosa/core/model/instance/utils/TreeUtilities.java, core/src/org/javarosa/core/util/DataUtil.java
Merging 2.19 release fixes back into master
=> 2.19 Release Reconcilliation

core/resources/test_nested_multiplicities.xml, core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/condition/EvaluationContext.java, core/src/org/javarosa/xpath/expr/XPathPathExpr.java, core/test/org/javarosa/core/form/api/test/TextFormTests.java, core/test/org/javarosa/core/model/test/FormDefTest.java, core/test/org/javarosa/core/model/test/QuestionDefTest.java, core/test/org/javarosa/core/test/FormParseInit.java, core/test/org/javarosa/form/api/test/FormEntryControllerTest.java, core/test/org/javarosa/xpath/expr/test/XPathPathExprTest.java
Added some more tests while trying to reproduce a bug that turned out to be a xpath syntax error.
=> Simple xpath expression tests while trying to reproduce bug

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/condition/Condition.java, core/src/org/javarosa/core/model/condition/EvaluationContext.java, core/src/org/javarosa/core/model/condition/Recalculate.java, core/src/org/javarosa/core/model/condition/Triggerable.java, core/src/org/javarosa/core/model/instance/TreeReference.java, core/src/org/javarosa/core/model/trace/EvaluationTrace.java, core/src/org/javarosa/core/model/trace/EvaluationTraceSerializer.java, core/src/org/javarosa/core/model/trace/StringEvaluationTraceSerializer.java, core/src/org/javarosa/form/api/FormEntryModel.java, core/src/org/javarosa/xpath/XPathConditional.java, core/src/org/javarosa/xpath/expr/XPathArithExpr.java, core/src/org/javarosa/xpath/expr/XPathBoolExpr.java, core/src/org/javarosa/xpath/expr/XPathCmpExpr.java, core/src/org/javarosa/xpath/expr/XPathEqExpr.java, core/src/org/javarosa/xpath/expr/XPathExpression.java, core/src/org/javarosa/xpath/expr/XPathFilterExpr.java, core/src/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/org/javarosa/xpath/expr/XPathNumNegExpr.java, core/src/org/javarosa/xpath/expr/XPathNumericLiteral.java, core/src/org/javarosa/xpath/expr/XPathPathExpr.java, core/src/org/javarosa/xpath/expr/XPathStringLiteral.java, core/src/org/javarosa/xpath/expr/XPathUnionExpr.java, core/src/org/javarosa/xpath/expr/XPathVariableReference.java, util/schema-gen/.classpath, util/schema-gen/src/org/javarosa/engine/XFormPlayer.java, util/schema-gen/src/org/javarosa/engine/models/EvaluationLevelJsonSerializer.java
Enables debug and visualization of XPath evaluation paths and drastically improves debugging capabilities on complex logic.
=> Add facilities for tracing XPath Evaluation 

core/src/org/javarosa/core/model/trace/StringEvaluationTraceSerializer.java, core/src/org/javarosa/xpath/expr/XPathArithExpr.java, core/src/org/javarosa/xpath/expr/XPathBoolExpr.java, core/src/org/javarosa/xpath/expr/XPathCmpExpr.java, core/src/org/javarosa/xpath/expr/XPathEqExpr.java
For J2ME compatibility, remove occurrences of String.format introduced by debug tracing PR.
=> Remove occurrences of String.format.

core/src/org/javarosa/xpath/expr/XPathFuncExpr.java
=> Revert "WIP: XPathFuncExpr linting and style"

core/src/org/javarosa/model/xform/XFormSerializingVisitor.java
This is really spammy in the touchform logs. any chance we can do away with it?
@ctsims @wpride
=> Remove println

core/src/org/javarosa/core/model/instance/DataInstance.java, core/src/org/javarosa/core/model/instance/TreeReference.java, core/test/org/javarosa/core/model/test/TreeReferenceTest.java
Figured I'd merge all the 2.21 fixes into master, even though the release isn't done.
Cross-requested with
https://github.com/dimagi/commcare/pull/80
https://github.com/dimagi/commcare-odk/pull/285
=> Merging 2.21 into master

core/src/org/javarosa/xform/parse/XFormParser.java
=> Remove title println

core/resources/test_setvalue_predicate.xml, core/src/org/javarosa/core/model/actions/SetValueAction.java, core/src/org/javarosa/xpath/XPathNodeset.java, core/test/org/javarosa/core/model/test/FormDefTest.java
Setvalue actions were not properly handling single reference bindings that resolved through a predicate expression.
=> Fix and Regression for SetValue issue.

j2me/entity-select/src/org/javarosa/entity/model/Entity.java, j2me/entity-select/src/org/javarosa/entity/model/view/EntitySelectView.java
http://manage.dimagi.com/default.asp?169125
J2ME doesn't actually support pixel-based columns, but it should still handle percentage-based ones.
Cross-requested with commcare and commcare-odk
=> Support pixel-based case list column widths

core/src/org/javarosa/core/model/QuestionString.java
=> remove override annotations for j2me

core/src/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
Quick update to allow different prototype factories when deserializing data in mocks.
=> Test Harness Improvement for dummy storage

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/GroupDef.java, core/src/org/javarosa/xform/parse/XFormParser.java
An old PR that I had to recreate because of merging issues:
Method level docs, a few variable renames and generics annotations.
=> GroupDef related comments/minor refactors

core/src/org/javarosa/form/api/FormEntryPrompt.java
addresses bug found here
http://manage.dimagi.com/default.asp?173228
originally fixed on master here
https://github.com/dimagi/javarosa/pull/103
=> Cherry pick constraint fix

core/src/org/javarosa/core/model/QuestionDef.java, core/src/org/javarosa/core/model/QuestionString.java, core/test/org/javarosa/core/form/api/test/TextFormTests.java
Fixed the serializations for text form tests, and fixed the tests so they run now.
fix for
http://manage.dimagi.com/default.asp?171349#973889
=> [CommCare 2.22] Fixed J2ME Build

j2me/entity-select/src/org/javarosa/entity/model/view/EntitySelectView.java
http://manage.dimagi.com/default.asp?176010
=> Fix NullPointerException in genStyleFromHints

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/xform/parse/XFormParser.java
J2ME compatibility fix for https://github.com/dimagi/javarosa/pull/105
=> Remove generics annotations because of J2ME

core/src/org/javarosa/xform/parse/XFormParser.java
Didn't quite get https://github.com/dimagi/javarosa/pull/116 right.
=> Remove generics annotations because of J2ME (Round II)

core/src/org/javarosa/xform/util/XFormUtils.java, util/schema-gen/.classpath, util/schema-gen/src/org/javarosa/engine/MockupProviderFactory.java, util/schema-gen/src/org/javarosa/engine/XFormEnvironment.java, util/schema-gen/src/org/javarosa/engine/XFormPlayer.java, util/schema-gen/src/org/javarosa/engine/models/Mockup.java, util/schema-gen/src/org/javarosa/engine/xml/FormInstanceParser.java, util/schema-gen/src/org/javarosa/engine/xml/XmlUtil.java, util/schema-gen/src/org/javarosa/xform/schema/FormOverview.java, util/schema-gen/src/org/javarosa/xform/schema/FormTranslationFormatter.java, util/schema-gen/src/org/javarosa/xform/schema/Harness.java, util/schema-gen/src/org/javarosa/xform/schema/InstanceSchema.java
Minor updates to XForms CLI code to allow printing out state more easily, and to integrate with the CommCare CLI push
=> Minor updates to XForms CLI code

core/src/org/javarosa/xform/util/XFormUtils.java
Fix for buffered input stream breaking build, imports from JR implementation now
=> 1.3 Library Fix

util/schema-gen/src/org/javarosa/xform/schema/FormInstanceLoader.java, util/schema-gen/src/org/javarosa/xform/schema/FormInstanceValidator.java, util/schema-gen/src/org/javarosa/xform/schema/Harness.java
Enable JavaRosa form runner CLI to load particular form instances
Try it out with: 
```
java -jar form_translate.jar runinstance form.xml instance.xml
```
=> Extend CLI interface to load form instances

core/src/org/javarosa/core/model/instance/TreeElement.java
Remove conditionals from TreeElement.populate that have test expressions that are never satisfied.
=> Remove no-op equiv piece of logic in TreeElement.populate

core/src/org/javarosa/core/model/Action.java, core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/instance/FormInstance.java, core/src/org/javarosa/core/model/instance/TreeElement.java, core/src/org/javarosa/form/api/FormEntryController.java, core/src/org/javarosa/form/api/FormEntryModel.java, core/src/org/javarosa/xform/parse/XFormParser.java, util/schema-gen/src/org/javarosa/xform/schema/FormInstanceLoader.java
- Removed javadoc method params that didn't have comments associated with them
- Removed unused arguments from methods
Cross-request: https://github.com/dimagi/commcare-odk/pull/419
__Only review after merging https://github.com/dimagi/javarosa/pull/122__
=> Cleanup of comments & unused args while working on Form Instance Loading

build.gradle
Update gradle build to also build schema-gen harness jar (into build/libs/harnes.jar)
Cross-requested with https://github.com/dimagi/commcare-odk/pull/471
=> Gradle harness

build.gradle
To invoke it: ```gradle check jacocoTestReport```
=> Add code coverage plugin to gradle

build.gradle
Set up fatjar to properly include project resources and dependencies
=> JavaRosa Form Runner CLI build

util/schema-gen/src/org/javarosa/engine/XFormPlayer.java
Updated player to post process forms and provide useful information about whether execution succeeded, and how to return the produced instance
X-Requested with
https://github.com/dimagi/commcare/pull/130
=> Updated inline player to perform processing

core/src/main/java/org/javarosa/core/services/storage/StorageManager.java
Added the ability to completely reset a storage manager which we need to be able to effectively use sandboxing during tests
=> Super small storage manager change needed for session tests.

core/.classpath, j2me/core/.classpath, j2me/objects/org.javarosa.user/.classpath, j2me/shared-resources/.classpath
makes j2me builds work again locally
=> Fixed locale j2me build process structure

core/src/test/java/org/javarosa/core/model/instance/test/DummyInstanceInitializationFactory.java
More typo artifacts from https://github.com/dimagi/javarosa/pull/155
=> Extend, dont' implement, InstanceInitializationFactory

core/src/main/java/org/javarosa/core/model/condition/pivot/RangeHint.java, core/src/test/java/org/javarosa/core/model/test/ConstraintTest.java, core/src/test/resources/test_constraints.xml
http://manage.dimagi.com/default.asp?176697#982290
If there is more than one pivot (IE both a > and <) we should just not use the hint because they're likely opposing
=> fix constraint pivot

build.gradle, core/src/main/java/org/javarosa/core/model/data/SelectMultiData.java, util/schema-gen/src/org/javarosa/engine/XFormPlayer.java
CLI Didn't used to support multiselect questions correctly
=> Fix for multiselect questions in CLI

core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Fix for: http://manage.dimagi.com/default.asp?180647
Fixed a major performance issue where the bulk tree element lookup would do a ton of double format tests that were very slow
=> Performance improvement for fixture lookups

core/src/main/java/org/javarosa/core/model/FormIndex.java
Helper methods for https://github.com/dimagi/commcare-odk/pull/648
=> Helper methods for form hierarchy view

core/src/main/java/org/javarosa/core/model/FormIndex.java
Prepping 2.23.1 odk hotfix which will include changes made by https://github.com/dimagi/commcare-odk/pull/648, which depends on https://github.com/dimagi/javarosa/pull/165
=> form hierarchy helper code for 2.23 hotfix

util/schema-gen/src/org/javarosa/engine/XFormEnvironment.java, util/schema-gen/src/org/javarosa/engine/XFormPlayer.java
Minor improvements to the CLI so Matt can more easily fix ICDS issues
X-Requested with: https://github.com/dimagi/commcare/pull/175
=> Quick CLI improvements

core/src/main/java/org/javarosa/core/util/DAG.java
Needed for 
https://github.com/dimagi/commcare/pull/178/files
=> Minor DAG updates for extension case change

core/src/main/java/org/javarosa/form/api/FormEntryPrompt.java
Cross https://github.com/dimagi/commcare-odk/pull/813
=> Add helper for select question markdown

core/src/main/java/org/javarosa/core/util/DAG.java
Changes to DAG class to support: https://github.com/dimagi/commcare/pull/223
(also cross: https://github.com/dimagi/commcare-odk/pull/910)
=> Validate cases DAG before case purge

core/src/main/java/org/javarosa/form/api/FormEntryController.java
Hopefully fix build break by https://github.com/dimagi/javarosa/pull/224
=> Add back descendIntoNewRepeat

core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java
Fix for missing stack overflow import in 
https://github.com/dimagi/javarosa/pull/215/files
=> Fix for missing import

core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java
Ugh, right, stackoverflow and outofmemory are "merged" on cldc
Fix for
https://github.com/dimagi/javarosa/pull/215/files
=> CLDC compatible Fix for stack overflow

core/src/main/java/org/javarosa/core/model/instance/ConcreteTreeElement.java
Update concrete tree element method name to match updates in https://github.com/dimagi/javarosa/pull/214/files
=> BuildRef -> buildRef

core/src/main/java/org/javarosa/core/model/data/GeoPointData.java
Cross-requested with https://github.com/dimagi/commcare-odk/pull/986.
=> Getters for altitude and accuracy

core/src/main/java/org/javarosa/core/model/User.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/transport/HttpUserRegistrationTranslator.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/utility/UserModelProcessor.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/view/LoginForm.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/view/UserForm.java, j2me/objects/org.javarosa.user/test/org/javarosa/user/model/test/UserTests.java
cross: https://github.com/dimagi/commcare-odk/pull/979, https://github.com/dimagi/commcare/pull/243
=> Clean up User.java during PIN password work

core/src/main/java/org/javarosa/core/model/SelectChoice.java
2.26 version of https://github.com/dimagi/javarosa/pull/236
=> repeat changes for 2.26

core/src/main/java/org/javarosa/form/api/FormEntryPrompt.java
Fix for http://manage.dimagi.com/default.asp?213023
=> Cache itemset choices once they are populated

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/FormIndex.java
Add back in a function that was removed here https://github.com/dimagi/javarosa/commit/6aedc0570c521a272b7ca0846764bcd2c52c9dba
Needed by touchforms
@phillipm
=> Add back in function used by touchforms

core/src/main/java/org/javarosa/form/api/FormEntryPrompt.java
Cache itemset choices once they are populated.
Version in master https://github.com/dimagi/javarosa/pull/238
=> 2.25.3 hotfix -- Make repeat groups work with lookup tables

core/src/main/java/org/javarosa/xform/parse/XFormParser.java
We call constraints validations in public facing text
See http://manage.dimagi.com/default.asp?217679
=> constraint -> validation

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/condition/Triggerable.java, core/src/main/java/org/javarosa/xpath/XPathConditional.java, core/src/main/java/org/javarosa/xpath/XPathLazyNodeset.java
Breaking out refactor portion of https://github.com/dimagi/javarosa/pull/251 into separate PR for easier reviewing, hopefully
=> FormDef / Triggerable refactors

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/actions/Action.java
J2ME compat fix for https://github.com/dimagi/javarosa/pull/243
=> clear -> removeAllElements

core/src/main/java/org/javarosa/core/model/utils/GeoPointUtils.java, core/src/main/java/org/javarosa/core/util/Map.java, core/src/main/java/org/javarosa/core/util/OrderedHashtable.java
Fix some j2me build failures that were introduced by https://github.com/dimagi/javarosa/pull/261
=> Fix j2me build failures due to linting

build.gradle
@phillipm fix for https://github.com/dimagi/javarosa/pull/259
=> Add correct classes, use correct main

core/src/main/java/org/javarosa/form/api/FormEntrySession.java
introduced by https://github.com/dimagi/javarosa/pull/248
=> fix j2me build error

core/src/main/java/org/javarosa/form/api/FormEntryAction.java, core/src/main/java/org/javarosa/form/api/FormEntrySession.java, core/src/main/java/org/javarosa/form/api/FormEntrySessionReplayer.java, core/src/test/java/org/javarosa/form/api/test/FormEntrySessionTest.java
Follow up to build errors introduced by https://github.com/dimagi/javarosa/pull/248
Don't use `Serializable` because J2ME is a :sob: :sob:
=> Manually serialize form entry session

core/src/main/java/org/javarosa/form/api/FormEntryController.java
revert function being made private here https://github.com/dimagi/javarosa/commit/dd2f56e86cc2d6c4446642e8039150eb250894f6
=> Make public function used by TouchForms

core/src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
https://github.com/dimagi/javarosa/pull/270 wasn't quite ready to go
=> expose another method

core/src/test/java/org/javarosa/xpath/test/XPathEvalTest.java
Last javarosa PR to support https://github.com/dimagi/commcare-odk/pull/1122
=> Expose one more method

core/src/main/java/org/javarosa/core/model/FormDef.java
Fix for http://manage.dimagi.com/default.asp?212637
Cross https://github.com/dimagi/touchforms/pull/208
Cross https://github.com/dimagi/commcare-hq/pull/11138
Allow FormDef to be initialized in "Edit form" mode which deactivates the retriggering of the end of form action
=> Track whether FormDef is being edited

core/src/main/java/org/javarosa/core/model/data/helper/Selection.java
Goes with PR Feedback for https://github.com/dimagi/commcare/pull/270
=> add selection index

.gitignore, core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/xform_tests/itext_function.xml, util/schema-gen/src/org/javarosa/engine/XFormEnvironment.java
Had some gnarly merge conflicts in `FormDef` between https://github.com/dimagi/javarosa/pull/290 and https://github.com/dimagi/javarosa/pull/285 that warrant a close look
=> 2.27 backmerge

core/src/main/java/org/javarosa/model/xform/XFormSerializingVisitor.java
Missed a glue file in
https://github.com/dimagi/javarosa/pull/292#discussion_r61766515
=> Missing file from error propogation fix

core/src/main/java/org/javarosa/core/model/utils/DateUtils.java, core/src/main/java/org/javarosa/core/util/DataUtil.java, j2me/communication/src/org/javarosa/service/transport/securehttp/HttpAuthenticator.java, j2me/core/src/org/javarosa/j2me/file/J2meFileReference.java, j2me/form-entry/src/org/javarosa/utilities/media/MediaUtils.java, j2me/javarosa-app/src/org/javarosa/demo/applogic/JRDemoContext.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/view/LoginForm.java
Another build fix for https://github.com/dimagi/javarosa/pull/304
=> add needed imports

core/src/main/java/org/javarosa/core/model/data/GeoPointData.java, core/src/main/java/org/javarosa/core/model/data/SelectMultiData.java, core/src/main/java/org/javarosa/core/model/utils/DateUtils.java, core/src/main/java/org/javarosa/core/model/utils/QuestionPreloader.java, core/src/main/java/org/javarosa/core/util/DataUtil.java, core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, j2me/communication/src/org/javarosa/service/transport/securehttp/HttpAuthenticator.java, j2me/core/src/org/javarosa/j2me/file/J2meFileReference.java, j2me/form-entry/src/org/javarosa/utilities/media/MediaUtils.java, j2me/javarosa-app/src/org/javarosa/demo/applogic/JRDemoContext.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/view/LoginForm.java
hotfix version of https://github.com/dimagi/javarosa/pull/304 (and subsequent build-fix commits)
=> 2.27.5 hotfix
