core/src/org/javarosa/core/model/instance/TreeReference.java, core/src/org/javarosa/xpath/expr/XPathFuncExpr.java, core/test/org/javarosa/core/model/test/TreeReferenceTest.java, core/test/org/javarosa/xpath/test/XPathEvalTest.java, j2me/buildfiles/build.xml
Removed HG requirement from build process.
Removed crypto tests, since code is no longer included in builds
Updated XPath Eval code to include potential for path driven tests again
Added subreference tests to treereference class tests
added tests for nodeset v. arg list polymorphism
updated treereference docs
Fixed bug with min/max/sum functions taking in argument lists that are paths
=> Fix for min/max not working with paths and argument lists

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/services/locale/Localizer.java, core/src/org/javarosa/xform/parse/XFormParser.java, core/src/org/javarosa/xform/util/XFormUtils.java
Fixing bug where when <output> structures in labels are malformed (example below), the xpath parser throws a message which bubbles up but makes no sense to the end user,
"Dependency cycle in <output>s; recursion limit exceeded!!"
This message should instead simply specify something like:
"Malformed expression: TEXT_OF_EXPRESSION_HERE"
Example:
<output ref="instance('casedb')/casedb/case[@case_id=current()/../../@id)]/case_name"/>
=> Output dep cycle parse error

core/src/org/javarosa/core/model/instance/utils/TreeUtilities.java, core/src/org/javarosa/xpath/expr/XPathEqExpr.java, core/src/org/javarosa/xpath/expr/XPathFuncExpr.java, core/test/org/javarosa/xpath/test/XPathEvalTest.java
Added a compliment of new tests to ensure predicate matching follows expected semantics to prevent regressions, and fixed an issue resulting in inconsistent predicate matching behaviors when unknown data types weren't being evaluated numerically
=> Fix for Predicate Optimization Evaluation Bug

core/build.properties, core/build.xml, j2me/buildfiles/build.xml
Round 2, now without extraneous commits from other branches :)
Unit tests can now be built/run from core build file via 'ant test'
Notes:
- Commit c748cb9 removes 'clean' as a dep for core project compilation. Will this break any automated builds we have in places like jenkins?
- The only changes to j2me/buildfiles/build.xml are in commit  418b333 and are purely whitespace and retabbing
=> Adding core tests build

j2me/form-entry/src/org/javarosa/formmanager/view/singlequestionscreen/screen/SingleQuestionScreen.java
Fix for OQPS not working properly when repeats overflow the number of question templates in the form template.
Doesn't actually fix the progress bar (it'll just look full for the rest of the form)
http://manage.dimagi.com/default.asp?160462
=> Nokia Phone Repeat Index Fix

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/condition/Condition.java, core/src/org/javarosa/core/model/condition/Triggerable.java, core/src/org/javarosa/core/model/instance/TreeReference.java, core/src/org/javarosa/core/model/instance/TreeReferenceLevel.java, core/src/org/javarosa/xpath/XPathConditional.java, core/test/org/javarosa/core/model/test/TreeReferenceTest.java
In prep for working on some reference related bugs I'm reading through code, cleaning up comments and adding tests
I've noted changes that are worthy of a 2nd look
=> Cursory clean-up of TreeReference code

core/resources/trigger_and_current_tests.xml, core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/core/model/condition/EvaluationContext.java, core/src/org/javarosa/core/model/condition/IConditionExpr.java, core/src/org/javarosa/core/model/condition/Triggerable.java, core/src/org/javarosa/xpath/XPathConditional.java, core/src/org/javarosa/xpath/expr/XPathPathExpr.java, core/test/org/javarosa/core/model/test/FormDefTest.java
Fixes bug where "current()" in the following tag doesn't expand to "/data/display":
<bind nodeset="/data/display" relevant="count(/data/a[@id='id'][. = current()/../show]) &gt; 0"/>
This occurred because XPathConditional.getTriggers() didn't propagate the "original" context, it only propagated the local context, so when identifying what node we should be referencing, the correct target of current() isn't available.
Depends on [PR 71](https://github.com/dimagi/javarosa/pull/71) being merged first
[FogBugz Ticket 112628](http://manage.dimagi.com/default.asp?112628)
=> Current and original context fix

core/src/org/javarosa/core/model/instance/TreeReference.java, core/test/org/javarosa/core/model/test/TreeReferenceTest.java
Fixes an issue from the TreeReference refactor which resulted in exposure of the original object's predicate set.
=> Predicate Exposure Bug

util/schema-gen/src/org/javarosa/engine/XFormPlayer.java, util/schema-gen/src/org/javarosa/xform/schema/Harness.java
Added basic evaluation to the command line player, should make it faster and easier to test and evaluate expressions against form inputs.
=> Extend Eval Functionality to Command Line Player

core/test/org/javarosa/core/model/test/CustomFuncTest.java
I changed the FormInitParser constructor, and this test was using the old constructor.
=> Fixed construction of FormInitParser in a test

core/src/org/javarosa/core/model/instance/DataInstance.java, core/src/org/javarosa/core/model/instance/TreeReference.java, core/test/org/javarosa/core/model/test/TreeReferenceTest.java
Fix contextualize to copy over multiplicity info from context reference if it will make the reference in question more specific, without overwriting existing multiplicity info.
Fixes [this ticket](http://manage.dimagi.com/default.asp?167350#932438)
=> Have 'contextualize' copy mult info.

core/test/org/javarosa/core/model/test/TreeReferenceTest.java
I thought wildcard parsing was broken when it occurred in the middle of a path (/foo/*/bar), so I created this test... turns out it wasn't broken, but I'll leave the test in.
=> Test for specializing wildcard during contextualization

core/src/org/javarosa/xform/parse/XFormParser.java
Reverts dimagi/javarosa#94
@wpride @ctsims 
Makes sense, I think muffling stdout is the way to go in touchforms then. Though it would be nice when it threw an error we had this info
=> Revert "Remove title println"

core/src/org/javarosa/form/api/FormEntryPrompt.java
2.22 bug fix where we were crashing when the constraint message was being retrieved when it wasn't set. the existing code already had the logic for this, I just wasn't polymorphing correctly
http://manage.dimagi.com/default.asp?171245
=> use the old code to fallback more elegantly

core/src/org/javarosa/core/model/FormDef.java, core/src/org/javarosa/form/api/FormEntryModel.java, core/src/org/javarosa/xform/parse/XFormParser.java, core/src/org/javarosa/xpath/XPathConditional.java, util/schema-gen/src/org/javarosa/xform/schema/FormOverview.java
An old PR that I had to recreate because of merging issues:
Method level comments relating to triggers.
Made triggerIndex private and expose it through documented methods as a means to better understand its role.
=> Comments and field privatization for triggers

core/src/org/javarosa/core/model/instance/TreeElement.java
Minimal changeset version of https://github.com/dimagi/javarosa/pull/124 for 2.22
Form Instance loading doesn't correctly copy element attributes for leaf nodes.
Fix for http://manage.dimagi.com/default.asp?170392
=> Form instance loading doesn't handle leaf attributes (2.22)

core/src/org/javarosa/core/model/instance/TreeElement.java
Form Instance loading doesn't correctly copy element attributes for leaf nodes.
Fix for http://manage.dimagi.com/default.asp?170392
__Only review/merge after https://github.com/dimagi/javarosa/pull/123 is merged__
=> Form instance loading doesn't handle leaf attributes

core/test/org/javarosa/core/model/test/TreeReferenceTest.java
Fix for Tree Reference Test checking for the wrong boolean on a predicate
=> Fix for malformed TreeReference test

core/build.gradle
Jenkins was report test failures because the build ran but tests weren't updated.
This is just because gradle is smarter than jenkins.
The fix is to update the timestamps on the test results.
=> Update test report timestamps so jenkins doesn't report test failures

build.gradle
In order to use the XFormPlayer in CommCare CLI tools, we need to expose the harness jar as a configuration here.
=> Create a build configuration for use in commcare/build.gradle

core/src/main/java/org/javarosa/core/model/instance/TreeReference.java, core/src/main/java/org/javarosa/core/model/instance/TreeReferenceLevel.java, core/src/main/java/org/javarosa/core/services/storage/util/DummyIndexedStorageUtility.java
Migrated dummy storage to require an intentional prototype factory implementation, and fixed a few places where the PF wasn't being passed through objects
Fixes 
http://manage.dimagi.com/default.asp?179023#994114
X-Requested in commcare
=> Force dummy storage to be intentional on prototype factory

core/src/main/java/org/javarosa/xform/parse/XFormParser.java
-stop parseControl from falsely raising an unused attributes warning for elements that have their own parse method, but use parseControl as a sub-routine, by passing in that element's specific list of used attributes.
-add "ref" as a used attribute for an 'upload' element, since it is missing
=> stop parseControl from raising false unused attr warning

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/instance/DataInstance.java, core/src/main/java/org/javarosa/core/util/CacheTable.java
@ctsims @benrudolph this fixes the issue by just wiping the cache when we delete a repeat. this happens rarely enough (not at all in ODK) that I think this is acceptable for now. Didn't want to spend too much time on this since it'll (hopefully) be addressed when we refactor the session into java
=> fix delete repeat bug

core/src/main/java/org/javarosa/core/services/storage/StorageFullException.java
https://github.com/dimagi/javarosa/pull/149 tries to invoke a `StorageFullException` constructor that takes a `String` arg, which crashes when built on Jenkins, because that constructor doesn't exist. Add it.
=> Make StorageFullException take message in constructor

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/instance/TreeReference.java, core/src/main/java/org/javarosa/core/model/instance/TreeReferenceLevel.java, core/src/main/java/org/javarosa/core/util/DataUtil.java, core/src/main/java/org/javarosa/xpath/expr/XPathArithExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathBinaryOpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathBoolExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathCmpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathEqExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathExpression.java, core/src/main/java/org/javarosa/xpath/expr/XPathFilterExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathNumNegExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathNumericLiteral.java, core/src/main/java/org/javarosa/xpath/expr/XPathOpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathQName.java, core/src/main/java/org/javarosa/xpath/expr/XPathStep.java, core/src/main/java/org/javarosa/xpath/expr/XPathStringLiteral.java, core/src/main/java/org/javarosa/xpath/expr/XPathUnaryOpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathUnionExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathVariableReference.java, core/src/main/java/org/javarosa/xpath/parser/ast/ASTNodeBinaryOp.java, core/src/main/java/org/javarosa/xpath/parser/ast/ASTNodeFilterExpr.java
Due to the interdependence of the `hashCode` and `equals` contracts (see [hashCode docs](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html#hashCode%28%29)), whenever one is overridden, it is pretty important to override the other.
For all the implementers of `XPathExpression` this was being done, but in a very round about way via the `toString` implementation. It is important that the fields used to calculate `equals` are also used in determining the result of `hashCode` so the distance between the two implementations could lead to bugs.
This PR enforces that all implementers of `XPathExpression` explicitly override both `hashCode` and `equals`.
In addition, I removed some duplicate code between the implementations of `XPathBinaryOpExpr` by consolidating the `op` field …
=> Override hashCode whenever equals is overridden

core/src/main/java/org/javarosa/xpath/expr/XPathNumericLiteral.java
Fix for build error introduced by https://github.com/dimagi/javarosa/pull/168
```
[javac] Internal J2ME Polish class: <http://jenkins.dimagi.com/job/commcare-mobile/ws/application/build/real/Generic/CustomKeys/none/source/main/java/org/javarosa/xpath/expr/XPathNumericLiteral.java>:45: error: cannot find symbol
[javac]         return Long.valueOf(Double.doubleToLongBits(d)).hashCode();
[javac]                    ^
[javac]   symbol:   method valueOf(long)
[javac]   location: class Long
```
=> Don't use Long.valueOf

build.gradle
Useful to enable odk to import classes defined in the testing section of javarosa.
Cross-requested https://github.com/dimagi/commcare-odk/pull/671
=> Expose test source files to external projects

core/src/main/java/org/javarosa/xform/parse/XFormParser.java
Fixes issues with XForms that don't set a title or a name
=> Ensure that FormDef objects always have something set for a name

core/src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java
New DataInstance models weren't copying over the cache host in the copy constructor so Cache and Index behavior had broken. Fixes a bug for TDH and m2mdemo
=> Fix for Instance Caching

core/src/main/java/org/javarosa/core/log/FlatLogSerializer.java, core/src/main/java/org/javarosa/core/log/IFullLogSerializer.java, core/src/main/java/org/javarosa/core/log/LogEntry.java, core/src/main/java/org/javarosa/core/log/StreamLogSerializer.java, core/src/main/java/org/javarosa/core/reference/ResourceReference.java
- Random linting in logging files.
- Make `ResourceReference.getStream` raise a FileNotFoundException to enable returning a `MissingResource` status when an app install/update tries to install an app that is missing a multimedia file.
=> misc logging refactor & raise file not found

core/src/main/java/org/javarosa/core/model/Action.java, core/src/main/java/org/javarosa/core/model/actions/SetValueAction.java
This was breaking J2ME builds because it requires some sort of polymorphic externalization magic.
=> Revert change that makes externalizable class method abstract

core/src/main/java/org/javarosa/core/model/condition/Recalculate.java
Fixes:
http://manage.dimagi.com/default.asp?185916#BugEvent.1037054
Fix for issue with recalculates not implementing .equals, resulting in it being possible for a recalculate to equal another trigger from the parent logic.
=> Fix for recalculate equality checks

core/src/main/java/org/javarosa/core/model/instance/FormInstance.java, core/src/main/java/org/javarosa/form/api/FormEntryPrompt.java
Previously, if the question text or select options for one question in a question list were dependent upon the answer to a prior question in the group, the question text / select options would NOT get updated when a user changed their answer to the prior question. This fixes that.
cross: https://github.com/dimagi/commcare-odk/pull/762
=> Dynamic refreshing of question content in question lists

core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/test/java/org/javarosa/test_utils/ExprEvalUtils.java, core/src/test/java/org/javarosa/xpath/expr/test/XPathFuncExprTest.java, core/src/test/java/org/javarosa/xpath/expr/test/XPathPathExprTest.java
Throw the right exception when processing a xpath with `select-at` that attempts to select outside of the range.
Fix for crashes like https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/88e06e6f6fefd6e46c48cc88461f88d5
=> Catch out-of-bounds exception in selected-at

core/src/main/java/org/javarosa/core/services/Logger.java
Fixes null pointer exception when handling exceptions in commcare async tasks.
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/f861a24eede4d2259e6f13b378eebee7
=> Don't deref a null error message in logger

core/src/main/java/org/javarosa/core/model/data/DateTimeData.java, core/src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java
Don't really understand the implications of this change, but Sheel was getting `warning: unrecognized data type in xpath expr: org.javarosa.core.model.data.DateTimeData` and this fixes that.
Might be a fix for http://manage.dimagi.com/default.asp?186983
=> Check for DateTimeData in unpackValue

core/src/main/java/org/javarosa/form/api/FormEntryController.java
Introduce a method to allow for checking question constraints without evaluating triggerables triggered by the question
cross-requested: https://github.com/dimagi/commcare-odk/pull/839
=> Don't trigger triggerables on constraint check

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/instance/TreeReference.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/xform_tests/test_repeat_insert_duplicate_triggering.xml
When we contextualize the `current()` in something like `<bind nodeset="/data/treatments/iterate_over_meds/item/id" calculate="current()/../@id"/>` we conflate `@id` and `/id`, such that `@id` gets set instead of `/id`.
This wasn't coming up because we were always re-triggering thing twice which somehow hid this issue. But since https://github.com/dimagi/javarosa/pull/174 triggers are only fired once, so this issue arises.
The test cases I added fail when the fix is absent.
http://manage.dimagi.com/default.asp?188205
=> Contextualization was conflating attributes and normal nodes of the same name

core/src/main/java/org/javarosa/form/api/FormEntryModel.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/xform_tests/test_looped_form_index_fetch.xml
Context: http://manage.dimagi.com/default.asp?188096#1057212
Fix for bug where repeats were attempting to be contextualized against an incomplete reference when their creation was forced due to navigation. Basically we were using the "local" portion of a form index's reference, the piece for the current 'step' instead of representing the full index.
=> Fix for Navigation Bug with End-Form Repeats

core/src/main/java/org/javarosa/core/model/instance/FormInstance.java, core/src/main/java/org/javarosa/core/model/instance/TreeElement.java, core/src/main/java/org/javarosa/core/util/externalizable/LivePrototypeFactory.java, core/src/test/java/org/javarosa/core/model/instance/test/FormInstanceTest.java, core/src/test/resources/xform_tests/test_repeat_insert_duplicate_triggering.xml
Fixture migration commentSerializing TreeElement's attributes looses the data type encoded in it, causing problems with data storage, like xforrm dateTime types being treated as dates.
Attribute serialization has always been broken but I think some redundancy in trigger firing has masked that fact. The issue has probably arisen now that I've optimized trigger firing.
__Has potential to increase size of serialized form instances by ~25%__ I will address this by refactoring fixture storage to use files instead of db blobs, which have a 1mb limit. This will come in a subsequent PR and must also make into 2.26
http://manage.dimagi.com/default.asp?188492
cross-requested with https://github.com/dimagi/commcare/pull/220 and https://github.com/dimagi/commcare-odk/pull/905
=> Serialize attributes correctly & add serialization tests

core/src/main/java/org/javarosa/core/model/instance/TreeElement.java
Fix J2ME compat issue in https://github.com/dimagi/javarosa/pull/208/
`Vector.get` -> `Vector.elementAt`
=> J2ME: get -> elementAt

core/src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java
Fix issue where a case entry's date_modified attribute value doesn't have time information. Turns out since our current form serialization technique doesn't store type info, dispatching on `DateTimeData` wasn't a good thing to do.
I've fixed form serialization in 2.26 to keep type info, so the change this PR is reverting can be left in master.
Bug originates from https://github.com/dimagi/javarosa/pull/195, which I made thinking it would fix the issues addressed in the 2.24.2 hotfix, but it actually didn't. Hence we can revert the changes safely.
Ticket: http://manage.dimagi.com/default.asp?190661
=> 2.25.2 hotfix: Revert dispatch on datetime in unpack

core/src/main/java/org/javarosa/core/model/data/GeoPointData.java, core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/test/java/org/javarosa/core/model/test/GeoPointTests.java, core/src/test/resources/geopoint_tests.xml
Specification of distance function changed to return -1 when either argument is an empty string (or null). 
Previously, an exception would be thrown if an argument was null, and the location (0, 0, 0, 0) would be used for the empty string.
=> Distance between empty locations

core/src/main/java/org/javarosa/core/util/externalizable/DeserializationException.java
Permit setting throwable sources on deserializations when available on the current platform
Fix for https://github.com/dimagi/javarosa/pull/232 on j2me
=> J2ME Compatibility for deserialziation exceptions

core/src/main/java/org/javarosa/core/services/locale/Localization.java
Translation keys aren't available at certain points when installing app updates. Hence introduce `getWithDefault` that returns the default value if the key lookup fails.
=> Add safe localization method for use when translations might not be avail.

core/src/main/java/org/javarosa/core/model/data/DateData.java
mis-ordered calls in `readExternal` cause a NPE when DateDatas are deserialized. This particular situation likely never actually comes up, for reasons Clayton explained and I did not really follow well enough to repeat here... But I came across it in writing a test, and seems good to fix either way.
=> fix bug in deserialization of DateData

core/src/main/java/org/javarosa/core/model/condition/EvaluationContext.java, core/src/main/java/org/javarosa/core/model/utils/CacheHost.java, core/src/main/java/org/javarosa/core/model/utils/DateUtils.java
Cache intermediate date variable to avoid recomputing it. Saves a hundred or two milliseconds on case loading :turtle: :turtle: :turtle:
=> Minor optimizations/refactors with case loading

core/src/main/java/org/javarosa/xpath/XPathException.java, core/src/main/java/org/javarosa/xpath/XPathLazyNodeset.java, core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, core/src/test/java/org/javarosa/xpath/expr/test/XPathFuncExprTest.java, core/src/test/resources/xform_tests/test_position_with_ref.xml
Usages of `position(some_empty_ref)` were crashing CommCare with an `ArrayIndexOutOfBoundsException`.
Catch such errors and rethrow a more helpful `XPathTypeMismatchException` that can be caught further up and shown to the user. 
There are hundreds of such crashes on ACRA, here is one as an example: 
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/9f16e2fc08448dd30dd3e3d5f4acea97
=> Make position(empty_ref) throw XPathTypeMismatchException

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/condition/Triggerable.java, core/src/main/java/org/javarosa/core/model/instance/TreeReference.java, core/src/main/java/org/javarosa/xpath/XPathConditional.java, core/src/main/java/org/javarosa/xpath/XPathLazyNodeset.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/xform_tests/model_iteration_lookahead.xml
Android-level 'form save on complete' re-fires all triggerables.  Disabling this, for performance reasons, exposes a bug were triggerables that fire on repeat inserts and have expressions that reference future (to be inserted) repeat entries never get re-fired due to over contextualization. This has been fixed by generalizing the triggerable context where path predicates are present for intersecting references in the triggerable expression.
For instance:
```
<bind 
calculate="/data/myiterator/iterator[@id = current()/../target]/value" 
nodeset="/data/myiterator/iterator/target_value"/>
```
This calculation triggerable should fire for all entries in `/data/myiterator/iterator` because `/data/myiterator/iterator[@id = current()/../target]/value` might reference an entry of …
=> Trigger lookaheads correctly in model iteration

core/src/main/java/org/javarosa/core/model/instance/FormInstance.java, core/src/main/java/org/javarosa/core/model/instance/TreeElement.java
Some refactors and a switch of order of ops to avoid an NPE
=> Prevent NPE on when setting TreeElement root to empty ref

core/src/main/java/org/javarosa/core/model/instance/FormInstance.java
Add back in function used by Touchforms removed in https://github.com/dimagi/javarosa/commit/cbea2ba72473c844b3bf08f59f32d760e91fa620
@phillipm I know Jython causes an annoying state where its very unclear what functions are being used, but can you refrain from removing more functions from javarosa/core and commcare/[backend, cases] for the time being? Hopefully in the near future (2-3 months) we'll be off Jython and the spring repository will make clear what functions are being used
=> Add back in meta data function used by TF

core/src/main/java/org/javarosa/core/model/CoreModelModule.java, j2me/communication/src/org/javarosa/service/transport/securehttp/AuthenticatedHttpTransportMessage.java, j2me/communication/src/org/javarosa/services/transport/TransportManagerModule.java, j2me/communication/src/org/javarosa/services/transport/TransportPropertyRules.java
Fixes the J2ME build (Serialization issues again)
Adds a platform redirect on J2ME where if an https request has certificate failures, it redirects the user to an optional URL that allows the user to create an exception on the device 
cross-request: https://github.com/dimagi/commcare/pull/267
=> J2ME Build fix and Cert Redirect

core/src/main/java/org/javarosa/core/model/FormDef.java
I've been coming against residual NPE crashes where form loading fails because the `FormDef`'s `ActionController` doesn't fail hard when deserialization fails, but rather to deserializes to `null`.
This PR makes form deserialization fail when the `ActionController` can't be deserialized. This forces the form to be re-read from xml and re-serialized.
To reproduce, load a form using an intent on master, then build https://github.com/dimagi/commcare-odk/pull/1128 and load the same form. The change in how `IntentCallout` is serialized somehow causes the `FormDef` deserialization to not load the `ActionController` correctly.
This change makes it so that if we change the serialization scheme of `ActionController`, or I guess other things as seen in the reproduction steps above, then we won't …
=> Don't allow ActionController to deserialize to null; prevents NPE crash

core/src/main/java/org/javarosa/form/api/FormEntryAction.java, core/src/main/java/org/javarosa/form/api/FormEntrySession.java, core/src/main/java/org/javarosa/form/api/FormEntrySessionReplayer.java, core/src/test/java/org/javarosa/form/api/test/FormEntrySessionTest.java
Makes form replay robust to addition and deletion of questions, by changing 3 things:
1. Instead of matching widgets to actions using the FormIndex, use the actual path of the question (e.g. /data/name). This value works better as a unique identifier for a question/answer pairing because while app builders can change the question ID of a question, they do so much less often than they insert or delete questions. (And in the event that they have changed a question ID, all this will do is prevent the question from being repopulated; it won't break anything).
2. Don't assume that questions have to be replayed in the exact order that the set of `FormEntryAction`s is in. Instead, as you move through each question index in the form, just search the list of actions for an action with a matching …
=> Make form replay more robust

core/src/main/java/org/javarosa/core/model/instance/TreeElement.java
Adding an optional flag for assuming unique child names in `addChild()`, which enables us to skip the very inefficient step of checking what the multiplicity should be.
Also removing an unused flag from the same method.
cross-request: https://github.com/dimagi/commcare/pull/274
=> Optimize case list loading

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/xpath/expr/XPathArithExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathBinaryOpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathBoolExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathCmpExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathEqExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathUnionExpr.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/java/org/javarosa/xpath/expr/test/XPathBinaryOpExprTest.java, core/src/test/resources/xform_tests/test_display_conditions_regression.xml
Fix for binary operation expression equality bug introduced in  https://github.com/dimagi/javarosa/pull/168 where two different operation classes, like equality and comparative, could be equal if they had the same sub-expressions and operator number encoding.
Basically, 'a < b' and 'a = b' were being treated as the same triggerable condition.
Addresses this ticket http://manage.dimagi.com/default.asp?222850
=> Fix binary op expression equality logic

core/src/main/java/org/javarosa/xpath/expr/XPathFilterExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathPathExpr.java, core/src/main/java/org/javarosa/xpath/expr/XPathStep.java
Refactors and very simple caching of `XPathPathExpr.getReferenec()` which, as far as I've tested, has very small performance gains, but is worth doing based on its simplicity.
Review commit-by-commit
=> XPath related refactors and XPathPathExpr.getReference() caching

.gitignore, core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/xform_tests/itext_function.xml, util/schema-gen/src/org/javarosa/engine/XFormEnvironment.java
Fix for bugs where the itext calculation in xpath was always using the form's default locale, even if the app locale is different.
Needed for ICDS
Fogbugz:
http://manage.dimagi.com/?221785
cross-request: https://github.com/dimagi/commcare-odk/pull/1200
=> Fix for IText Calculations not properly initializing with the app locale

core/src/main/java/org/javarosa/xform/util/XFormSerializer.java
Significantly better handling of encoding errors when serializing documents, lets errors bubble up semantically.
=> Fix for bad error wrapping

core/src/main/java/org/javarosa/xform/util/XFormSerializer.java
Unicode characters that require "surrogates" will cause form saving to crash on certain older devices ([thanks for the 'fix' google](https://code.google.com/p/android/issues/detail?id=64108)).
Catch these exceptions and rethrow in a manner that can be shown to the user in an actionable way. Either the user inputted that character, or the form builder did; in both cases, showing them this will allow them to react accordingly
=> Tell user when CommCare's unable to save unsupported unicode

util/schema-gen/src/org/javarosa/xform/schema/Harness.java, util/schema-gen/src/org/javarosa/xform/schema/JSONReporter.java
Make the form_translate jar output UTF-8 when possible. This will make error messages with unicode more helpful on HQ.
Instead of seeing `?????` in the image below, we will see real unicode
Changes `form_translate.jar validate` output from:
```
{"problems":[],"fatal_error":"Invalid XPath in value set action declaration: '??????'\n    Problem found at nodeset: \/html\/head\/model\/setvalue\n    With element <setvalue event=\"xforms-ready\" ref=\"\/data\/emoji_list\/question3\" value=\"??????\"\/>\n","fatal_error_expected":true,"validated":false}
```
to
```
{"problems":[],"fatal_error":"Invalid XPath in value set action declaration: 'हिन्दी'\n    Problem found at nodeset: \/html\/head\/model\/setvalue\n    With element <setvalue event=\"xforms-ready\" ref=\"\/data\/emoji_list\/question3\" …
```
=> Make validator write unicode output

core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java
Show the user an error when they use a bad regexp in a `replace` xpath expression, like 
`replace("abbc", "a(.*c", "$1")`
=> Tell user when `replace` uses bad regexp

util/schema-gen/src/org/javarosa/xform/schema/Harness.java
Fix issue introduced by https://github.com/dimagi/javarosa/pull/294 where the output stream wasn't correctly set, hence breaking the ability to pipe output of `form_translate.jar validate` to other files
=> Correctly set out stream for validator jar

core/src/main/java/org/javarosa/core/services/locale/LocalizationUtils.java
Was tired of seeing `Invalid line (#703) read: 'custom.acknowledgement='. No value follows the '='.` due to adding `custom.acknowledgement=` in https://github.com/dimagi/commcare-odk/pull/1216/files#diff-8dfb39970e36cd4bcc88809249fa7bdeR677
Also fix lint warnings in `LocalizationUtils`
=> Remove warning of empty localization, refactors

core/src/main/java/org/javarosa/core/model/data/GeoPointData.java, core/src/main/java/org/javarosa/core/model/data/SelectMultiData.java, core/src/main/java/org/javarosa/core/model/utils/DateUtils.java, core/src/main/java/org/javarosa/core/model/utils/QuestionPreloader.java, core/src/main/java/org/javarosa/core/util/DataUtil.java, core/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java
As part of performance improvements for ICDS Daily Feeding Form: Using built in String.split() method instead of DateUtils.split() improves form load time with a case load of 400 from 1 min 40 seconds to 27 seconds
=> Use (much faster) built-in String.split() method when possible

core/src/main/java/org/javarosa/core/util/DataUtil.java, j2me/communication/src/org/javarosa/service/transport/securehttp/HttpAuthenticator.java, j2me/core/src/org/javarosa/j2me/file/J2meFileReference.java, j2me/form-entry/src/org/javarosa/utilities/media/MediaUtils.java, j2me/javarosa-app/src/org/javarosa/demo/applogic/JRDemoContext.java, j2me/objects/org.javarosa.user/src/org/javarosa/user/view/LoginForm.java
Fix build failure caused by https://github.com/dimagi/javarosa/pull/304 (I forgot to check for method usage in the j2me code). I'm not bothering to have any of the j2me code paths use the `StringSplitter` logic because we know they will always just call the j2me implementation.
=> fix j2me method calls

core/src/main/java/org/javarosa/core/model/FormDef.java, core/src/main/java/org/javarosa/core/model/instance/TreeElement.java, core/src/test/java/org/javarosa/core/model/test/FormDefTest.java, core/src/test/resources/multiple_repeats.xml
Fix for: http://manage.dimagi.com/default.asp?229136
Appears that this has been broken for a while, but is (obviously) a very rare situation. Essentially, when an element was deleted we were grabbing all of its parent's children then iterating through these and reducing the multiplicity if they exceeded a certain threshold. This works fine when a repeat is within a group or there are no other repeats, but when (as in this case) the repeat's parent element has other repeat elements as children AND these children's multiplicities exceed the threshold, then we incorrectly reduce the multiplicities. The solution is to check that the deleted node and the child nodes are the "same" in every sense except multiplicity. 
This fix is admittedly very inelegant, but since the needed functionality is …
=> Repeat delete fix

core/src/main/java/org/javarosa/core/model/instance/utils/TreeUtilities.java
Follow-up to https://github.com/dimagi/commcare-android/pull/1307 where I changed the behavior to not modify the vector arguments.
http://manage.dimagi.com/default.asp?231366
=> Return result of union, not in-going set

core/src/main/java/org/javarosa/core/model/FormIndex.java
Fix for http://manage.dimagi.com/default.asp?231236 because if two form index instances have similar hashcodes it messes up select-one butotn restores due to https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/views/widgets/SelectOneWidget.java#L50
=> Better hashcode for FormIndex
